apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      nodeSelector:
        kafka-producer: "true"
      containers:
      - name: producer
        image: shallowdream2/mykafka:latest
        command: ["python", "producer.py"]
        env:
        - name: KAFKA_BROKER
          value: my-kafka-cluster-kafka-bootstrap:9092
        - name: TOPIC_NAME_1
          value: test-topic
        - name: TOPIC_NAME_2
          value: test-topic-2

