apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: strimzi-cluster-operator
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  - nodes
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - namespaces
  - serviceaccounts
  - resourcequotas

  verbs:
  - get
  - list
  - watch
  - create  # 确保添加了创建权限
  - update
  - patch
  - delete

- apiGroups: ["apps"]
  resources:
  - deployments
  - replicasets
  - statefulsets

  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch

- apiGroups: ["policy"]
  resources:
  - poddisruptionbudgets

  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch

- apiGroups: ["kafka.strimzi.io"]
  resources:
  - "*"  # 为了确保所有资源都被授权，使用通配符
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
- apiGroups: ["networking.k8s.io"]
  resources:
  - ingresses
  - networkpolicies
  
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
- apiGroups: ["extensions"]
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: strimzi-cluster-operator
subjects:
- kind: ServiceAccount
  name: strimzi-cluster-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: strimzi-cluster-operator
  apiGroup: rbac.authorization.k8s.io

